### PR TITLE
Add support for SyncAdapters

### PR DESCRIPTION
**Pull request by danijoo**
This adds support for SyncAdapters in Kodein. They also have a context and I just ran into a case where if would be helpful to be able to use kodein together with them :)

### CODE REVIEW

**Comment by SalomonBrys** [comment]
Looks great,
however the second commit undoes the first.
Indeed, the service import is useless, so why put it back in the second commit ?

**Comment by danijoo** [comment]
I think the second one only removed an unused import of Service class. The extension function for SyncAdapter should be there!

**Comment by SalomonBrys** [comment]
The extension function for SyncAdapter is there in the second commit. But this commit also re-puts the unused service import

**Comment by SalomonBrys** [comment]
Your work has been incorporated in v2.4.0.
I've squashed the commits.

Thanks for your work.

**Pull request closed without merging**
