### PR TITLE
Initialize the injector before super.onCreate in components

### LINKED ISSUE #50: "UninjectedException: Value has not been injected" after orientation change
When I use an kodein activity and and kodein fragment, the first start of the activity works perfect. But if i rotate the device, the fragment gets recreated before onCreate of the the activity is finished.

That  means that the kodein value is not injected when the fragment needs it.

This could be easily fixed if in all kodein activities you call initializeInjector **BEFORE** super.onCreate(savedInstanceState)

-> a workaround for the moment is to use the interface versions and call this function in the activities yourself before super.onCreate(savedInstanceState)

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initializeInjector()
}
```

should be changed to

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        initializeInjector()
        super.onCreate(savedInstanceState)
}
```

in KodeinActivity, KodeinFragmentActivity and KodeinAppCompatActivity

### PR DESCRIPTION
**Pull request by eygraber**
Fixes #50

### CODE REVIEW

**Comment by coreydowning** [comment]
I wonder if a more correct fix for this issue would be to have `Fragment` injection happen in [onActivityCreated](https://developer.android.com/reference/android/app/Fragment.html#onActivityCreated(android.os.Bundle)).

**Comment by eygraber** [comment]
The only issue with that is that it occurs after the `View` is created, and users most likely would require some of their dependencies before then.

**Comment by coreydowning** [comment]
Stumbled across this in the Dagger 2 docs:

> When members injection is required (as discussed above), prefer to inject as early as possible. For this reason, DaggerActivity calls AndroidInjection.inject() immediately in onCreate(), before calling super.onCreate(), and DaggerFragment does the same in onAttach(), which also prevents inconsistencies if the Fragment is reattached.

https://google.github.io/dagger/android.html#when-to-inject

Sounds like Kodein should follow suite.

**Comment by eygraber** [comment]
@coreydowning nice find!

@SalomonBrys seems like this is ready to be merged

**Comment by SalomonBrys** [comment]
Thanks a lot :)

**Pull request merged**
